services:
  react:
    container_name: react
    image: node:23.11.0-alpine
    ports:
      - "2000:2000"
    volumes:
      - ./front:/app/
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  nest:
    container_name: nest
    image: node:23.11.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app/
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    environment:
      - PORT=3000
